"""add friends_chat_name to group_listings

Revision ID: df479cf80ec3
Revises: f9b544b66a51
Create Date: 2026-02-21 16:23:06.597965

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df479cf80ec3"
down_revision: str | Sequence[str] | None = "f9b544b66a51"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group_listings",
        sa.Column("friends_chat_name", sa.String(length=12), nullable=False, server_default=""),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("group_listings", "friends_chat_name")
    # ### end Alembic commands ###
